services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: budgettracker
      POSTGRES_USER: budgetuser
      POSTGRES_PASSWORD: budgetpass123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
